server:
  port: 8888
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri:  https://github.com/DreamsChaser/spring-cloud-config/
          searchPaths: src/main/resource/public


